# Generated by Django 5.1.2 on 2024-11-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='imagess',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='titles',
        ),
    ]
